class HelloJava
{
	public static void main (String[] args)
	{
        String introduction = "\n###################################################### Introduction ######################################################\n";
        introduction += "* Java is an object-oriented, class-based programming language.\n";
		introduction += "* In the year 1995, Java language was developed.\n";
		System.out.println(introduction);

		String terminology = "\n###################################################### Terminology ######################################################\n";
		terminology += "* JVM - specification for runtime environment to execute java bytecode. for each java execution, a new JVM is created\n";
		terminology += "* ByteCode - Intermediate output generated by java compiler.\n";
		terminology += "* JDK - Development Kit for Java.\n";
		terminology += "* JRE - Implementation of JVM.\n";
		terminology += "* Garbage collector - take care of memory management.\n";
		terminology += "* Classpath - JRE search class file to load\n";
		terminology += "* Classpath - JRE search class file to load\n";
		System.out.println(terminology);

		String features = "\n###################################################### Features ######################################################\n";
		features += "* Platform independent\n";
		features += "* Object oriented programming language\n";
		features += "* Robust (Reliable)\n";
		features += "* Secure\n";
		features += "* Distributed\n";
		features += "* Multithreading\n";
		features += "* Portability\n";
		features += "* Sandbox execution - doesn't impact underlying system\n";
		features += "* Compiled and interpreted language\n";
		System.out.println(features);

	}
}